title: "Yi Zhu's Website"
description: "Welcome to my personal website, powered by Jekyll!"
author: "Yi Zhu"
url: "https://mat-zhu.github.io"
baseurl: "" # empty for root domain
theme: jekyll-theme-minimal

# Add MathJax support
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Enable MathJax support
mathjax: true

navigation:
  - title: "Home"
    url: "/"
  - title: "links"
    url: "/links"
  - title: "talks-and-travels"
    url: "/talks-and-travels"
